### ISSUE TITLE
Smaller network for the cluster VPC

### ISSUE THREAD

**Issue by deromemont** [Qovery/terraform-provider-qovery#57]
I want to put a smaller network to connect it to our infrastructure

Like this: 10.85.86.0/23

Response: 
Could not create cluster 'test-dev', unexpected error: 400 Bad Request - Invalid Config: Invalid VPC IP: The VPC Subnet 10.85.86.0/23 is not valid.

**Comment by benamib** [comment]
Hello @deromemont

At the moment we only supports a certain range of VPC IP
- `10.X.0.0/16` _with X [0, 255]_
- `172.16.0.0/16` 
- `192.168.0.0/16`
- `198.19.0.0/16`

I'll check with the team if we can add more IPs to this range and get back to you afterward

**Comment by benamib** [comment]
Hi @deromemont

I spoke with the product team about your request. 

This feature has not been planned on the roadmap at the moment since we didn't have any request regarding more customization on vpc subnets until now. 

The reason behind this limited subnet range is to follow AWS best practices to avoid painful / non possible modifications at a later date. 

As it's not related to the Qovery's Terraform Provider specifically, I invite you to submit a feature request on our [roadmap](https://roadmap.qovery.com/b/5m13y5v6/feature-ideas) for it to be taken into account by the product team.
