### ISSUE TITLE
Secret environment variables

### ISSUE THREAD

**Issue by json-lbtn** [Qovery/terraform-provider-qovery#58]
Hello mates 🍃 

Concerning the use of environment variables, we wanted to know if it was planned to allow the recovery of secrets, for example we want to create an alias on the URL of a managed database.
Unfortunately we have access problems : 

![image](https://user-images.githubusercontent.com/99829196/169718308-dada0f7c-cab8-4ef3-aa86-bbc9396c416a.png)

![image](https://user-images.githubusercontent.com/99829196/169718317-25b1be9c-3324-4ada-83dc-b609f1189c2f.png)

Is there already a roadmap about this ?

**Comment by benamib** [comment]
Hi @json-lbtn 

Yes we planned that on the roadmap but I can't say for sure when this will be released 
The thing with secrets is that we won't be able to get their values since it's supposed to be sensitive data that the api don't return.

**Comment by json-lbtn** [comment]
Hello @benamib 🍃 
Let me re-launch this topic at least so that we are aligned on a possible solution roadmap concerning this topic.

We just want to be able to link our database to our APIs using the qovery terraform provider.

Maybe splitting the internal host from the password in the URL environment variable (which is the only part to keep secret after all) in a DATABASE_INTERNAL_HOST environment variable accessible in clear text is a solution, at least temporary and already accessible?

**Comment by evoxmusic** [comment]
Hi @json-lbtn , I see with Bilel tomorrow and he will come back to you 👍

**Comment by benamib** [comment]
Hey @json-lbtn 

Sorry for the delay

To be able to help you on this I need to clarify some points. 

If I understood correctly, you are looking to connect to your database from your application however you can't do so because you don't have access to the DATABASE_URL_INTERNAL ? 
Are you also looking for other informations, for exemple do you need to get the PASSWORD of the database ? 
Are the database and the application in the same Qovery environment ?

Also I wanted to make sure you were aware that every applications will have built-in secrets set automatically with DATABASE_URL for all the databases within the same environment (see image bellow). 

<img width="1154" alt="Screenshot 2022-06-06 at 16 09 13" src="https://user-images.githubusercontent.com/2103806/172177742-90a88bee-f076-4ee6-b3e7-177b8040842d.png">

However the secret name contains part of the database id, this is why we usually recommend setting an alias for those (see [documentation](https://hub.qovery.com/docs/using-qovery/configuration/application/#database) here)

I feel like if we could solve you issue by allowing creation of aliases within the terraform provider, what do you think about this solution ?

**Comment by benamib** [comment]
Hi @json-lbtn,

Your are now abled to get the INTERNAL_HOST in clear text directly in the [database resource](https://registry.terraform.io/providers/qovery/qovery/latest/docs/resources/database#internal_host). 

I'll close this one since there is nothing else to do regarding environment secrets.
